### PR TITLE
fix #64 adds settable check functions for cert/serverCert

### LINKED ISSUE #64: Support a way to check if a cert/serverCert can be saved
To extend enrollment via the identity library, `SetCert` or `SetServerCert` are called, but they may fail for various reasons. Some of those reasons warrant not starting the extend enrollment process at all, as it will never succeed. Add a way to check to see if the `serverCert` and `cert` are "settable."

### PR DESCRIPTION
**Pull request by andrewpmartinez**
Done to support openziti/ziti#2984

### CODE REVIEW

File: identity.go [hunk 1]
```diff
@@ -289,7 +343,10 @@ func (id *ID) SetCert(pemStr string) error {
 		id.Config.Cert = StoragePem + ":" + pemStr
 		return fmt.Errorf("could not save client certificate, location scheme not supported for saving (%s):\n%s", id.Config.Cert, pemStr)
 	case StorageFile, "":
-		f, err := os.OpenFile(id.Config.Cert, os.O_RDWR, 0664)
+
+		absPath, err := filepath.Abs(id.Config.Cert)
```
Comment (dovholuknf) [inline identity.go:347]: ignoring this err on purpose?

File: identity.go [hunk 2]
```diff
@@ -326,7 +383,10 @@ func (id *ID) SetServerCert(pem string) error {
 		id.Config.ServerCert = StoragePem + ":" + pem
 		return fmt.Errorf("could not save client certificate, location scheme not supported for saving (%s): \n %s", id.Config.Cert, pem)
 	case StorageFile, "":
-		f, err := os.OpenFile(id.Config.ServerCert, os.O_RDWR, 0664)
+
+		absPath, err := filepath.Abs(id.Config.ServerCert)
```
Comment (dovholuknf) [inline identity.go:387]: same here fwiw, err isn't checked. just making sure it's intentional

File: identity.go [hunk 3]
```diff
@@ -76,9 +76,15 @@ type Identity interface {
 	// StopWatchingFiles reversed WatchFiles.
 	StopWatchingFiles()
 
+	// IsCertSettable returns nil if the "cert" certificate storage supports writing, used before calling SetCert()
+	IsCertSettable() error
```
Comment (dovholuknf) [inline identity.go:80]: imo, it seems strange for an 'Is' function to return error not a bool

**Review by dovholuknf — APPROVED** [review]

File: identity.go (hunk 1 above)
Comment (andrewpmartinez) [reply identity.go:357]: fixed

File: identity.go (hunk 2 above)
Comment (andrewpmartinez) [reply identity.go:397]: fixed

File: identity.go (hunk 3 above)
Comment (dovholuknf) [reply identity.go:80]: :D if you say so. I'd just prefer the "Is" to be "Verify" or "Check" or literally anything that isn't "Is" but i don't care all that much

**Review by plorenz — APPROVED** [review]
some linter errors, but otherwise looks good
